python run_image_classification.py \
    --model_name_or_path google/vit-base-patch16-224 \
    --train_dir ./data/train \
    --validation_dir ./data/val \
    --output_dir ./outputs \
    --remove_unused_columns False \
    --do_train \
    --do_eval \
    --push_to_hub \
    --push_to_hub_model_id vit-base-cat_or_dog \
    --learning_rate 2e-5 \
    --num_train_epochs 5 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --logging_strategy steps \
    --logging_steps 10 \
    --evaluation_strategy epoch \
    --save_strategy epoch \
    --load_best_model_at_end True \
    --save_total_limit 3 \
    --seed 1337 \
    --ignore_mismatched_sizes \
    --cache_dir ./cache